In [ ]:
from google.cloud import bigquery
import pandas
import time
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [8]:
client = bigquery.Client(location="US")
print("Client creating using default project: {}".format(client.project))

Client creating using default project: data

In [9]:
query = """
    SELECT
      a.*,
      b.* EXCEPT (Customer_ID),
      c.* EXCEPT (Customer_ID)
    FROM
      `data.churn.wls_churn_master_target_t1` AS a
    JOIN
      `data.churn.wls_customer_demographics_t1` AS b
    ON
      a.Customer_ID =b.Customer_ID
    JOIN
      `data.churn.wls_billing`  AS c
    ON
      a.Customer_ID =c.Customer_ID
"""
query_job = client.query(
    query,
    # Location must match that of the dataset(s) referenced in the query.
    location="US",
)  # API request - starts the query

df = query_job.to_dataframe()
df

,Customer_ID,mrc_current_month,mvsf_br_amt_current_month,mvsf_mrc_current_month,num_subs_current_month,num_voice_subs_current_month,num_nonvoice_subs_current_month,rev_current_month,churn,n_distinct_srvc_prov_state_cd_current_month,...,payment_method_cd_r_ind_current_month,kb_payment_method_cd_c_ind_current_month,kb_payment_method_cd_d_ind_current_month,kb_payment_method_cd_r_ind_current_month,auto_payment_method_cd_ca_ind_current_month,auto_payment_method_cd_cc_ind_current_month,auto_payment_method_cd_dd_ind_current_month,kb_auto_payment_method_cd_c_ind_current_month,kb_auto_payment_method_cd_d_ind_current_month,kb_auto_payment_method_cd_r_ind_current_month
0,404,285.00,285.00,0.0,1,0,1,285.00,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,3545,6389.87,6389.87,0.0,1,0,1,6389.87,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,4333,10000.00,10000.00,0.0,1,0,1,10000.00,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,6027,440.86,440.86,0.0,1,0,1,440.86,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,7592,0.95,0.95,0.0,1,1,0,0.95,0.0,0,...,1,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9585,8586,1212.50,1212.50,1209.5,80,0,80,1212.50,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9586,9253,3688.63,3682.63,3983.5,83,76,7,3662.63,1.0,0,...,0,0,0,0,0,0,0,0,0,0
9587,3987,2755.23,2401.23,2650.0,85,48,37,2401.23,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9588,2656,5122.26,5122.26,4996.0,90,90,0,5122.26,0.0,0,...,0,0,0,0,0,0,0,0,0,0
9589,6403,1941.27,2058.01,1543.0,93,22,71,1941.27,0.0,0,...,0,0,0,0,0,0,0,0,0,0